### ISSUE TITLE
[Question] Trouble generating invite token

### ISSUE THREAD

**Issue by gustavogattino** [PyBites-Open-Source/karmabot#52]
Hello there!
I'm sorry if this is a really noob question and out of the right place to ask, but I'm having a hard time finding where to generate the _invite token_ to use on `KARMABOT_SLACK_INVITE_USER_TOKEN`.

I'm not sure if this is the same token used for [channels.invite](https://api.slack.com/methods/channels.invite) API call or if it is the _Legacy tokens_, which cannot be created anymore.

I receive the following message when running `slackbot`:
```
09-22 18:42 root         INFO     Script started
09-22 18:42 root         INFO     Loading environmental variables from .karmabot.
Connecting to DB with postgres://user42:pw42@localhost:5432/karmabot
DB connection successful
09-22 18:42 slackclient.client WARNING  Failed RTM connect
Traceback (most recent call last):
  File "/home/maul/.local/lib/python3.8/site-packages/slackclient/client.py", line 140, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "/home/maul/.local/lib/python3.8/site-packages/slackclient/server.py", line 163, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
09-22 18:42 root         ERROR    Connection Failed, invalid token?
```

I'd really appreciate your assistance on where can I generate this token.

**Comment by pogross** [comment]
Hi there. Now worries, this is the right place to ask questions 😃 

As your error states `WARNING  Failed RTM connect` I suspect it has something to do with your `KARMABOT_SLACK_TOKEN` which is the one that lets the bot join the server and watch messages. This should generally work at least with the "general" channel. 

`KARMABOT_SLACK_INVITE_USER_TOKEN` is only relevant if a new channel is created after the bot joined / is active. So, if something goes wrong with the invite token the bot just can't join new channels but should always work on the "general" channel. We will take a look into the deprecation of the API Endpoint and how to fix this for the Invite token.

Can you check if the SLACK_TOKEN is available and properly inserted in your `.karmabot` / env variables?
> KARMABOT_SLACK_TOKEN The [auth token](https://slack.com/help/articles/115005265703-Create-a-bot-for-your-workspace) for your bot. You can find the token from the [My Apps](https://api.slack.com/apps/) page for your Karmabot under OAuth & Permissions --> Tokens for Your Workspace --> Bot User OAuth Access Token. It starts with xoxb-.

If the problem persists maybe @pmayd can take a look.

**Comment by pmayd** [comment]
I think it is the case that you need a legacy token token, because karmabot is using an older version of the slack client api where this token was required. I had the same problems with the now standard apps. 

In any case, the tokens required by karmabot are the tokens listed under OAuth & Permission, not the App credentials. So you don't need client secret etc. The tokens you need begin with `xoxp` and `xoxb` 

![Screenshot_1](https://user-images.githubusercontent.com/9614291/93931930-b9214400-fd1f-11ea-9908-8709d38effea.png)

**Comment by gustavogattino** [comment]
Thanks a lot for the fast reply! :O
I really appreciate the assistance.

>In any case, the tokens required by karmabot are the tokens listed under OAuth & Permission, not the App credentials. So you don't need client secret etc. The tokens you need begin with xoxp and xoxb

Thanks! I actually didn't had a `OAuth Access Token` entry, just the bot one. I created the `User Token Scopes` and reinstalled the bot:
![Capture](https://user-images.githubusercontent.com/1775265/93934026-ea3a4e00-fcf8-11ea-83b5-b83a871b432e.PNG)

> Can you check if the SLACK_TOKEN is available and properly inserted in your .karmabot / env variables?

I'm using a .karmabot file:
```
KARMABOT_SLACK_USER=A01BJAR9DHP
KARMABOT_SLACK_TOKEN=xoxb-**
KARMABOT_SLACK_INVITE_USER_TOKEN=xoxp-***
KARMABOT_DATABASE_URL=postgres://user42:pw42@localhost:5432/karmabot
KARMABOT_GENERAL_CHANNEL=CC2RJNMU7
KARMABOT_ADMINS=U016V0UMPM2,UC1862KPB,U016G5SHZT8
```
I've tried swapping both xoxb and xoxp tokens to see if it would work, but I'm still receiving the same error message. Channel `CC2RJNMU7` is our #general channel.
![Capture2](https://user-images.githubusercontent.com/1775265/93934194-2b326280-fcf9-11ea-85d3-c69eceb03640.PNG)

If it helps somehow, I'm using the following
- bot token scopes: channels:history, channels:join, channels:read, chat:write, chat:write.public, im:history, im:read, im:write
- user token scopes: channels:history, channels:read, channels:write, im:history, im:read, im:write
- system: ubuntu server 20.04.01 (fresh install, installed jus the bare minimum to run the karmabot and docker db)
- workspace access: owner

Once again, thanks a lot for helping!

**Comment by pmayd** [comment]
I now remember what I had to do to get it working. The problem is that the apps you create in the Slack API are not compatible with karmabot (we will change this!).

So you need to explicitly create a classic app, that is the name in Slack speech. The strange thing is that you do not see any option to do so in the Slack API landing page where you create your apps. This option is hidden. So go to:
https://api.slack.com/legacy/custom-integrations/legacy-tokens#migrating-from-legacy

And from there follow the link to create your classical Slack app. You should be redirected to your app overview page with your apps and a dialog should open to create a new app. And now in the title you should see the suffix (classic). Only tokens from classic apps work with the current version of karmabot.

**Comment by pogross** [comment]
This should go to the README until we updated the client ⚠️

**Comment by gustavogattino** [comment]
Thanks a lot for the help! Following @pmayd instructions allowed me to add the bot on my workspace!
